### ISSUE TITLE
As a new or experienced user, I can add a project to the planner

### ISSUE THREAD

**Issue by Nineves** [AY2122S2-CS2113-F10-1/tp#6]
...so that I can better organize my project.

**Comment by YaxinJoy** [comment]
Some parts in the handleUserInput() (_tp/src/main/java/cpp/projects/commandhandler.handleUserInput(), line 29_) may exist errors. 

`public void handleUserInput(ProjectList projectList, String userInput) {
        commands = userInput.split(" ");

        switch (commands[0].toLowerCase()) {
        case "addproject": //add a project into list
            projectList.addProject(commands[1]);
            System.out.println("____________________________________________________________");
            System.out.println(commands[1] + " Added.");
            System.out.println("____________________________________________________________");
            break;
        case "deleteproject": //delete a project based on its name
            projectList.deleteProject(commands[1]);
            System.out.println("____________________________________________________________");
            System.out.println(commands[1] + " Deleted.");
            System.out.println("____________________________________________________________");
            break;
        case "viewproject": //view all project(s) by name
            projectList.printProject();
            break;
        default:
            System.out.println("____________________________________________________________");
            System.out.println("Unknown command.");
            System.out.println("____________________________________________________________");
            break;
        }

    }`

If the length of a project name is longer than 2, for example, `addproject CS2113 tP`. The program will only save `CS2113` since the parameter passed to addProject() is `commands[1]`. 

Besides, I have fixed the issues for deleting a project (cannot use `projectList.delete(title)` directly). The parameter passed to ArrayList.delete() is the index of the item you want to delete, not its name.

Others look good!
